//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphTestDaniel1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxEmail
    {
        public int ID { get; set; }
        public Nullable<int> UserPrincipalID { get; set; }
        public string UserEmail { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public string CCEmail { get; set; }
        public string BCCEmail { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> DateTimeSent { get; set; }
        public Nullable<System.DateTime> DateTimeImported { get; set; }
        public string Sender { get; set; }
        public string ToEmailNames { get; set; }
        public string CCEmailNames { get; set; }
        public string BCCEmailNames { get; set; }
        public Nullable<int> RecipientCount { get; set; }
    }
}
