//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphTestDaniel1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HuddleSmtpEntities : DbContext
    {
        public HuddleSmtpEntities()
            : base("name=HuddleSmtpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserPrincipal> UserPrincipals { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<InboxEmail> InboxEmails { get; set; }
        public virtual DbSet<SentEmail> SentEmails { get; set; }
        public virtual DbSet<UserPrincipalTable> UserPrincipalTables { get; set; }
        public virtual DbSet<UserNotDoneYetInbox> UserNotDoneYetInboxes { get; set; }
        public virtual DbSet<UsersNotDoneYet> UsersNotDoneYets { get; set; }
    }
}
