//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphTestDaniel1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotDoneYetInbox
    {
        public long UniqueId { get; set; }
        public string UserEmail { get; set; }
        public string UserID { get; set; }
        public string DisplayName { get; set; }
    }
}
